# Generated by Django 3.2.5 on 2021-07-20 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pandatube', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ManyToManyField(blank=True, to='pandatube.CourseTag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pandatube.profile')),
            ],
        ),
    ]
