# Generated by Django 3.2.5 on 2021-08-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandatube', '0002_auto_20210809_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetag',
            name='course_num',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
