# Generated by Django 3.2.5 on 2021-08-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandatube', '0002_alter_video_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetag',
            name='course_describe',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coursetag',
            name='course_title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
