# Generated by Django 3.2.5 on 2021-07-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandatube', '0002_purchasedcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedcourse',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='courses', to='pandatube.CourseTag'),
        ),
    ]
