# Generated by Django 3.2.5 on 2021-08-11 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pandatube', '0003_auto_20210811_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursetag',
            old_name='course_title',
            new_name='course_subtitle',
        ),
    ]
