# Generated by Django 3.2.5 on 2021-08-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandatube', '0004_alter_coursetag_course_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetag',
            name='course_thumbnail',
            field=models.FileField(default='https://pandabase.sgp1.cdn.digitaloceanspaces.com/pandabase/default/default/default-video.jpg', upload_to=''),
        ),
    ]
