# Generated by Django 3.2.5 on 2021-08-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandatube', '0005_alter_coursetag_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetag',
            name='course_thumbnail',
            field=models.FileField(default='https://pandabase.ashblast.com/pandabase/default/default/default-course.jpg', upload_to=''),
        ),
    ]
