# Generated by Django 3.2.5 on 2021-07-28 09:55

from django.db import migrations, models
import pandatube.models


class Migration(migrations.Migration):

    dependencies = [
        ('pandatube', '0005_alter_coursetag_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetag',
            name='course_thumbnail',
            field=models.FileField(default='/default/default-course.jpg', upload_to=pandatube.models.course_thumbnail_path),
        ),
    ]
