# Generated by Django 3.2.5 on 2021-07-28 10:03

from django.db import migrations, models
import pandatube.models


class Migration(migrations.Migration):

    dependencies = [
        ('pandatube', '0006_alter_coursetag_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetag',
            name='course_thumbnail',
            field=models.FileField(default='settings.STATIC_URL/default/default-course.jpg', upload_to=pandatube.models.course_thumbnail_path),
        ),
    ]
