# Generated by Django 3.2.5 on 2021-08-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandatube', '0007_alter_coursetag_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetag',
            name='course_thumbnail',
            field=models.FileField(default='default/default-video.jpg', upload_to=''),
        ),
    ]
