# Generated by Django 3.2.5 on 2021-08-10 09:49

import django.core.validators
from django.db import migrations, models
import pandatube.models


class Migration(migrations.Migration):

    dependencies = [
        ('pandatube', '0008_alter_coursetag_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetag',
            name='course_thumbnail',
            field=models.FileField(default='default/default-video.jpg', upload_to=pandatube.models.course_thumbnail_path),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=pandatube.models.video_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_thumbnail',
            field=models.ImageField(default='media/default/default-video.jpg', upload_to=pandatube.models.video_thumbnails_path),
        ),
    ]
