# Generated by Django 3.2.5 on 2021-07-28 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pandatube', '0008_auto_20210728_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetag',
            name='course_tag',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pandatube.coursename'),
        ),
    ]
