# Generated by Django 3.2.5 on 2021-07-31 07:13

from django.db import migrations, models
import pandatube.models


class Migration(migrations.Migration):

    dependencies = [
        ('pandatube', '0009_alter_coursetag_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_thumbnail',
            field=models.ImageField(default='/default/default-video.jpg', upload_to=pandatube.models.video_thumbnails_path),
        ),
    ]
