# Generated by Django 3.2.5 on 2021-08-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandatube', '0010_video_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown'), ('H', 'Anonymous')], default=('H', 'Anonymous'), max_length=1),
        ),
    ]
