# Generated by Django 3.2.5 on 2021-08-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandatube', '0011_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetag',
            name='course_num',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
