# Generated by Django 3.2.5 on 2021-08-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandatube', '0012_alter_coursetag_course_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetag',
            name='course_num',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
